OCR_GARBAGE_PATTERNS = [
    r"[■□▪▫●○◆◇★☆♦♣♠♥]+",
    r"[\^~`]{2,}",
    r"[|!]{3,}",
    r"\.{5,}",
    r"\*{5,}",
    r"_{5,}",
    r"-{5,}",
    r"[^\x00-\x7F]{5,}",
    r"[A-Z\s]{50,}",
]

GOOGLE_TEXT_BLOCKS = [
    r"Google's\s+mission\s+is\s+to\s+organize\s+the\s+world's\s+information.*?(?:Google\s+Book\s+Search|search\s+engine).*?\n",
    r"This\s+is\s+a\s+digital\s+copy\s+of\s+a\s+book\s+that\s+was\s+preserved.*?(?:books\.google\.com|public\s+domain|Google\s+Book\s+Search).*?\n",
    r"About\s+Google\s+Book\s+Search.*?(?:books\.google\.com|Book\s+Search).*?\n",
    r"(?:Whether\s+a\s+book\s+is\s+in\s+the\s+public\s+domain|public\s+domain\s+in\s+the\s+United\s+States).*?Google.*?\n",
    r"(?:We\s+encourage\s+the\s+use\s+of\s+public\s+domain|Usage\s+guidelines|Please\s+do\s+not\s+remove\s+this).*?Google.*?\n",
]
GOOGLE_TEXT_COMPILED = [re.compile(p, re.IGNORECASE | re.DOTALL) for p in GOOGLE_TEXT_BLOCKS]

BOILERPLATE_KEYWORDS = [
    "copyright term has expired",
    "merely their custodians",
    "we also ask that you",
    "non-commercial purposes",
    "keep it legal",
    "copyright infringement",
    "discover the world",
    "search through the full text",
    "placing technical restrictions",
    "automated querying",
    "helping authors and publishers",
    "reach new audiences",
    "whether a book is still in copyright",
    "varies from country to country",
    "specific use of any specific book",
    "anywhere in the world",
    "public domain material",
    "hosted by",
    "authorized facsimile",
    "university microfilms",
    "microfilm-xerography",
    "acid-free paper",
    "ann arbor",
    "qooqle",
    "qoogle",
    "optical character recognition",
    "large amount of text",
    "please contact us",
    "in the custody of the",
    "university of california",
    "los angeles",
    "digitized by",
    "digital copy of a book",
    "public domain in the united states",
    "books.google",
    "hathitrust digital library",
    "generated by hathitrust",
]

HATHI_PATTERNS = [
    r"HathiTrust\s+Digital\s+Library[^\n]*\n",
    r"Generated\s+.*?HathiTrust[^\n]*\n",
    r"Public\s+Domain\s+.*?Google-digitized[^\n]*\n",
]

LIBRARY_PATTERNS = [
    r"(?i)university\s+of\s+\w+\s*[•·]\s*\w+",
    r"(?i)the\s+library\s+of\s+the\s+university",
    r"(?i)(?:bequest|gift)\s+of\s+[A-Z][^\n]{0,50}\n",
    r"(?i)public\s+domain.*?google",
    r"(?i)scanned\s+by\s+[^\n]{0,50}\n",
    r"(?i)from\s+the\s+collections?\s+of[^\n]*\n",
]

FRONT_STAMP_PATTERNS = [
    r"(?i)^university\s+of",
    r"(?i)^the\s+library",
    r"(?i)^public\s+library",
    r"(?i)^boston\s+public",
    r"(?i)^property\s+of",
    r"(?i)^in\s+the\s+custody",
    r"(?i)^accession",
    r"(?i)^call\s+n",
    r"(?i)^from\s+the\s+collection",
    r"(?i)^gift\s+of",
    r"(?i)^bequest\s+of",
    r"(?i)^presented\s+by",
    r"(?i)^digitized\s+by",
    r"(?i)^scanned\s+by",
    r"(?i)^oxford\s*$",
    r"(?i)^cambridge\s*$",
    r"(?i)^harvard\s*$",
    r"(?i)^yale\s*$",
    r"(?i)^cornell\s*$",
    r"(?i)^harvard\s+college",
    r"(?i)^harvard\s+university",
    r"(?i)^godfrey\s+lowell\s+cabot",
    r"(?i)^science\s+library",
    r"(?i)^widener\s+library",
    r"(?i)^received",
    r"(?i)^ex\s*libris",
    r"(?i)^sigill",
    r"(?i)^veri\s*tas",
    r"(?i)^ecclesia",
    r"(?i)^nov[\s:]+angl",
    r"(?i)^christo",
    r"(?i)^academiae",
    r"^[A-Z]{1,4}\s+\d{1,5}[\s.]",
    r"^\d{3,7}\s*$",
    r"(?i)^library\s+of\s+congress",
]
FRONT_STAMP_COMPILED = [re.compile(p) for p in FRONT_STAMP_PATTERNS]
STAMP_KEYWORD_COMPILED = [
    re.compile(p) for p in [
        r"(?i)\bharvard\b",
        r"(?i)college\s+library",
        r"(?i)university\s+library",
        r"(?i)ve\w{0,2}r?i?\s*[ts]\w?as",
        r"(?i)academiae",
        r"(?i)sigill\b",
        r"(?i)\bbequest\b",
        r"(?i)\bgift\s+of\b",
        r"(?i)\bclass\s+of\s+\d{4}\b",
    ]
]

PG_START = re.compile(r"\*{3}\s*START\s+OF\s+.*?PROJECT\s+GUTENBERG.*?\*{3}", re.IGNORECASE | re.DOTALL)
PG_END = re.compile(r"\*{3}\s*END\s+OF\s+.*?PROJECT\s+GUTENBERG.*?\*{3}", re.IGNORECASE | re.DOTALL)
HYPHEN_LINEBREAK_RE = re.compile(r"([a-z]{2,})-\n([a-z])")


def estimate_printable_ratio(text, sample_size=10000):
    sample = text[:sample_size]
    if not sample:
        return 0.0
    printable = sum(1 for c in sample if c.isprintable() or c in "\n\t")
    return printable / len(sample)


def count_ocr_artifacts(text):
    sample = text[:30000]
    return sum(len(re.findall(pattern, sample)) for pattern in OCR_GARBAGE_PATTERNS)


def remove_google_boilerplate(text):
    for pattern in GOOGLE_TEXT_COMPILED:
        text = pattern.sub("", text)
    kept = []
    for line in text.split("\n"):
        line_lower = line.lower()
        if "google" in line_lower and (len(line) < 100 or line_lower.find("google") < 50 or line_lower.find("google") > len(line) - 50):
            continue
        if any(kw in line_lower for kw in BOILERPLATE_KEYWORDS):
            continue
        if re.match(r"^\s*[Gg]\s*[Oo0]\s*[Oo0]\s*[Gg]\s*[Ll1]\s*[Ee3]\s*$", line):
            continue
        if line.strip() == "LIBRARY":
            continue
        kept.append(line)
    return "\n".join(kept)


def remove_hathi_boilerplate(text):
    for pattern in HATHI_PATTERNS:
        text = re.sub(pattern, "", text, flags=re.IGNORECASE)
    return text


def remove_library_stamps(text):
    for pattern in LIBRARY_PATTERNS:
        text = re.sub(pattern, "", text)
    return text


def strip_pg_boilerplate(text):
    start = PG_START.search(text)
    if start:
        text = text[start.end():]
    end = PG_END.search(text)
    if end:
        text = text[:end.start()]
    return text


def normalize_unicode(text):
    text = unicodedata.normalize("NFKC", text)
    replacements = {
        "ﬁ": "fi", "ﬂ": "fl", "ﬀ": "ff", "ﬃ": "ffi", "ﬄ": "ffl",
        "æ": "ae", "œ": "oe", "ſ": "s",
        "—": "--", "–": "-",
        "“": '"', "”": '"', "‘": "'", "’": "'",
        "…": "...", "\u00ad": "",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


def normalize_whitespace(text):
    text = text.replace("\t", " ")
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"[ \t]+$", "", text, flags=re.MULTILINE)
    text = re.sub(r"[ \t]{2,}", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def clean_ocr_artifacts(text):
    text = re.sub(r"^\s*[-\[]*\s*\d{1,4}\s*[-\]]*\s*$", "", text, flags=re.MULTILINE)
    text = re.sub(r"^\s*[a-zA-Z]\s*$", "", text, flags=re.MULTILINE)
    text = re.sub(r"^[^a-zA-Z]*$", "", text, flags=re.MULTILINE)
    return text


def reflow_text(text):
    paragraphs = text.split("\n\n")
    reflowed = []
    for para in paragraphs:
        line = para.replace("\n", " ")
        line = re.sub(r"  +", " ", line)
        reflowed.append(line.strip())
    return "\n\n".join(p for p in reflowed if p)


def strip_leading_garbage(text, max_lines=100):
    lines = text.split("\n")
    start_idx = 0
    for i, line in enumerate(lines[:max_lines]):
        stripped = line.strip()
        if not stripped:
            continue
        is_stamp = any(p.match(stripped) for p in FRONT_STAMP_COMPILED)
        if not is_stamp and len(stripped) < 80:
            is_stamp = any(p.search(stripped) for p in STAMP_KEYWORD_COMPILED)
        if is_stamp:
            continue
        alpha_count = sum(1 for c in stripped if c.isalpha())
        alpha_ratio = alpha_count / max(len(stripped), 1)
        word_count = len(stripped.split())
        is_content = (
            (len(stripped) > 40 and alpha_ratio > 0.5)
            or (alpha_ratio > 0.8 and word_count >= 3 and len(stripped) > 15)
            or (word_count >= 4 and alpha_ratio > 0.6)
        )
        if is_content:
            start_idx = i
            break
    return "\n".join(lines[start_idx:]) if start_idx > 0 else text


def scrub_front_matter_stamp_lines(text, max_lines=120):
    """Remove short institutional stamp lines that survive after a title/byline."""
    lines = text.split("\n")
    out = []
    for i, line in enumerate(lines):
        stripped = line.strip()
        if i < max_lines and len(stripped) < 90:
            if any(p.search(stripped) for p in STAMP_KEYWORD_COMPILED):
                continue
            if re.match(r"^\d[\d\s-]{8,}$", stripped):
                continue
        out.append(line)
    return "\n".join(out)


def remove_front_matter(text, max_scan=15000):
    text = strip_leading_garbage(text)
    text = scrub_front_matter_stamp_lines(text)
    markers = [
        r"(?i)^CHAPTER\s+[IVX\d]+",
        r"(?i)^BOOK\s+[IVX\d]+",
        r"(?i)^PART\s+[IVX\d]+",
        r"(?i)^INTRODUCTION\s*$",
        r"(?i)^PREFACE\s*\.?\s*$",
        r"(?i)^CONTENTS\s*$",
        r"(?i)^THE\s+PREFACE",
        r"(?i)^TO\s+THE\s+READER",
        r"(?i)^ADVERTISEMENT\s*$",
        r"(?i)^DEDICATION\s*$",
        r"(?i)^PROLOGUE\s*$",
    ]
    front = text[:max_scan]
    earliest = max_scan
    for pattern in markers:
        match = re.search(pattern, front, re.MULTILINE)
        if match and match.start() < earliest:
            earliest = match.start()
    return text[earliest:] if 200 < earliest < max_scan else text


def clean_text(text):
    text = remove_google_boilerplate(text)
    text = remove_hathi_boilerplate(text)
    text = remove_library_stamps(text)
    text = strip_pg_boilerplate(text)
    text = normalize_unicode(text)
    text = clean_ocr_artifacts(text)
    text = normalize_whitespace(text)
    text = HYPHEN_LINEBREAK_RE.sub(r"\1\2", text)
    text = reflow_text(text)
    text = remove_front_matter(text)
    return text.strip()


def structural_clean(text):
    if not isinstance(text, str) or len(text) < MIN_CHARS_RAW:
        return None, "too_short_raw"
    if estimate_printable_ratio(text) < MIN_PRINTABLE:
        return None, "low_printable"
    if count_ocr_artifacts(text) > MAX_OCR_ARTIFACTS:
        return None, "ocr_artifacts"
    cleaned = clean_text(text)
    if len(cleaned) < MIN_CHARS_CLEAN:
        return None, "too_short_clean"
    return cleaned, "ok"


def source_shards():
    files = list_repo_files_safe(SRC_REPO)
    shards = sorted([p for p in files if re.match(r"(^|.*/)shard_\d+\.parquet$", p)])
    if not shards:
        shards = sorted([p for p in files if p.endswith(".parquet")])
    print(f"Found {len(shards):,} source parquet shards.")
    return shards


def destination_shards():
    files = list_repo_files_safe(DST_REPO)
    return set(p for p in files if re.match(r"(^|.*/)shard_\d+\.parquet$", p))


def download_source_shard(path_in_repo):
    return hf_hub_download(
        repo_id=SRC_REPO,
        repo_type="dataset",
        filename=path_in_repo,
        token=HF_TOKEN,
        local_dir=SRC_CACHE,
    )


def output_path_for_source(path_in_repo):
    return Path(path_in_repo).name


SOURCE_SHARDS = source_shards()
